# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_code', models.IntegerField()),
                ('si_name', models.CharField(max_length=20)),
                ('gu_code', models.IntegerField()),
                ('gu_name', models.CharField(max_length=20)),
                ('dong_code', models.BigIntegerField()),
                ('dong_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housetype', models.CharField(db_column='houseType', max_length=1)),
                ('dealtype', models.CharField(db_column='dealType', max_length=1)),
                ('year', models.IntegerField(db_column='Year')),
                ('period', models.IntegerField(db_column='Period')),
                ('sidocode', models.IntegerField(db_column='sidoCode')),
                ('guguncode', models.IntegerField(db_column='gugunCode')),
                ('dongcode', models.BigIntegerField(db_column='dongCode')),
                ('deal_date', models.DateField()),
                ('bldg_area', models.FloatField(blank=True, db_column='BLDG_AREA', null=True)),
                ('bobn', models.CharField(blank=True, db_column='BOBN', max_length=11, null=True)),
                ('aptfno', models.CharField(blank=True, db_column='APTFNO', max_length=25, null=True)),
                ('deal_dd', models.CharField(blank=True, db_column='DEAL_DD', max_length=11, null=True)),
                ('deal_mm', models.IntegerField(blank=True, db_column='DEAL_MM', null=True)),
                ('bldg_nm', models.CharField(blank=True, db_column='BLDG_NM', max_length=100, null=True)),
                ('bubn', models.IntegerField(blank=True, db_column='BUBN', null=True)),
                ('bldg_cd', models.BigIntegerField(blank=True, db_column='BLDG_CD', null=True)),
                ('build_year', models.IntegerField(blank=True, db_column='BUILD_YEAR', null=True)),
                ('sum_amt', models.IntegerField(blank=True, db_column='SUM_AMT', null=True)),
                ('rent_amt', models.IntegerField(blank=True, db_column='RENT_AMT', null=True)),
                ('tot_area', models.FloatField(blank=True, db_column='TOT_AREA', null=True)),
                ('bldg_muse_nm', models.CharField(blank=True, db_column='BLDG_MUSE_NM', max_length=40, null=True)),
                ('lawd_cd', models.BigIntegerField(blank=True, db_column='LAWD_CD', null=True)),
                ('umd_nm', models.CharField(blank=True, db_column='UMD_NM', max_length=40, null=True)),
                ('right_gbn', models.IntegerField(blank=True, db_column='RIGHT_GBN', null=True)),
            ],
        ),
    ]
