# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_address2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address1',
        ),
        migrations.DeleteModel(
            name='Address2',
        ),
    ]
