# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_auto_20161123_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='bubn',
            field=models.CharField(blank=True, db_column='BUBN', max_length=100, null=True),
        ),
    ]
