# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0007_auto_20161125_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='realestate.Address'),
            preserve_default=False,
        ),
    ]
